# name: Flutter CI

# on:
#   push:
#     branches: ["*"]
#   pull_request:

# jobs:
#   ci:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1 — Checkout repository
#       - name: Checkout code
#         uses: actions/checkout@v5

#       - name: Decode secret file
#         run: |
#           echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > upload-keystore.jks

#         env:
#           ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

#       - name: Read the decoded file
#         run: |
#           echo "Decoded content is:"
#           cat upload-keystore.jks

#       # Step 2 — Setup Flutter SDK
#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.35.7'

#       # Step 3 — Install dependencies
#       - name: Install dependencies
#         run: flutter pub get

#       # Step 4 — Static analysis
#       - name: Analyze code
#         run: flutter analyze

#       # Step 5 — Format check
#       - name: Check formatting
#         run: dart format --output=none --set-exit-if-changed .

#       # Step 6 — Run tests + collect coverage
#       - name: Run tests
#         run: flutter test --coverage

#       # Step 7 — Upload artifacts (coverage folder)
#       - name: Upload coverage
#         uses: actions/upload-artifact@v4
#         with:
#           name: coverage
#           path: coverage/
